#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nis

. /etc/rc.librebsd

nis_start()
{
	:
}

nis_stop()
{
        /usr/local/www/librebsdUI/tools/cachetool.py expire
}


name="ix-nis"
start_cmd='nis_start'
stop_cmd='nis_stop'
            
load_rc_config $name
run_rc_command "$1"
